### ISSUE TITLE
Create help function

### ISSUE THREAD

**Issue by meharwalia** [MicrosoftStudentChapter/tech-week-discord-bot#5]
create a function which mentions all the commands which could be given to the bot, and is also triggered when someone joins the server

**Comment by vaibhavi4246** [comment]
I will work on this issue.

**Comment by SanyamWadhwa07** [comment]
coordinate accordingly....

**Comment by SanyamWadhwa07** [comment]
How do you want to approach this issue

**Comment by SanyamWadhwa07** [comment]
help function done
