### ISSUE TITLE
Create a register function

### ISSUE THREAD

**Issue by meharwalia** [MicrosoftStudentChapter/tech-week-discord-bot#6]
Create a function which allows the participants to register for the tech week by specifying their departments.

**Comment by PreetinderSinghBadesha** [comment]
@MW-5705 I would like to work with this issue

**Comment by Nehag-29** [comment]
pls assign this issue to me

**Comment by MankiratSingh1315** [comment]
@Nehag-29 coordinate with @DarkCoder26

**Comment by PreetinderSinghBadesha** [comment]
@Nehag-29 can you tell me how you want to approach this issue?
